version: "3"

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - shared-certs:/etc/nginx/ssl
    depends_on:
      - outline
      - minio
    networks:
      - outline-network


  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command: start-dev
    environment:
      KC_HOSTNAME : blakes-macbook-pro.local
      KC_HOSTNAME_PATH : /keycloak
      KC_PROXY : edge
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: secretpassword
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_URL: https://blakes-macbook-pro.local/keycloak/
      KEYCLOAK_URL: https://blakes-macbook-pro.local/keycloak/
      KEYCLOAK_FRONTEND_URL: https://blakes-macbook-pro.local/keycloak/
      KEYCLOAK_ADMIN_URL: https://blakes-macbook-pro.local/keycloak/admin
    networks:
      - outline-network
    depends_on:
      - keycloak-db
    volumes:
      - ./keycloak-data:/opt/keycloak/data
    ports:
      - "8080:8080"
  keycloak-db:
    image: postgres:15
    container_name: keycloak-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - ./keycloak-db-data:/var/lib/postgresql/data
    networks:
        - outline-network

  outline:
    image: outlinewiki/outline:latest
    container_name: outline
    env_file:
      - .env
    environment:
      - NODE_TLS_REJECT_UNAUTHORIZED = 0
      - URL=https://blakes-macbook-pro.local/
      - OAUTH2_PROVIDER_URL=https://nginx/keycloak/
      - PORT=3000
      - DATABASE_URL=postgres://outline:password@postgres:5432/outline
      - REDIS_URL=redis://redis:6379
      - STORAGE_DRIVER=s3
      - AWS_S3_UPLOAD_BUCKET_URL=https://blakes-macbook-pro.local:9000/outline
      - AWS_ACCESS_KEY_ID=outlineadmin
      - AWS_SECRET_ACCESS_KEY=supersecretpassword
      - AWS_S3_UPLOAD_BUCKET_NAME=outline
      - AWS_S3_UPLOAD_MAX_SIZE=26214400
      - AWS_S3_FORCE_PATH_STYLE=true
      - PGSSLMODE=disable
    extra_hosts:
      - "Blakes-macbook-pro.local:172.20.0.8"
    networks:
      - outline-network

  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=outline
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=outline
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - outline-network

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - outline-network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=outlineadmin
      - MINIO_ROOT_PASSWORD=supersecretpassword
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    volumes:
      - minio_data:/data
      - ./shared-certs/selfsigned.crt:/root/.minio/certs/public.crt
      - ./shared-certs/selfsigned.key:/root/.minio/certs/private.key
    networks:
      - outline-network

volumes:
  postgres_data:
  minio_data:
  shared-certs:

networks:
  outline-network:
